010 ' MUSICA CRAB CANNON'
015 ' COLECAO DE PROGRAMAS PARA MSX VOLUME 1'
020 PLAY "v10t120","v9t120"
030 PLAY "o3l2ce-gf","o3l4ce-go4cl8o3bo4cde-fe-dc"
040 PLAY "o2l12br4o3l2gf#","o4l8do3go3dfe-dco3babo4ce-"
050 PLAY "o3l2fee-d","o4l8dco3baga-b-o4d-co3b-a-gfgfga-a-"
060 PLAY "o3l4dd-co2bgo3ce-","o3l8b-gfe-dc-fgfe-db-"
070 PLAY "o3l2e-dce-","o3l8gfe-o4co3bagfe-de-go4co3gfg"
080 PLAY "o3l8gfgo4co3ge-de-fgabo4co3e-fg","o3l2e-cde-"
090 PLAY "o3l8a-de-fgfe-de-fga-b","o3l4fco2gbo3cd-"
100 PLAY "o3l8b-a-gfga-b-o4cd-o3b-a-gabo4d","o3l2e-eff#"
110 PLAY "o4l8e-co3babo4cde-fdo3go4dcde-f","o3l4ggr4o2bbo3aa"
120 PLAY "o4l8e-dco3bo4co3ge-c","o3l2ge-c"