10 ' EXEMPLOS DE OPERADORES 
12 ' ARITIMETICOS 
15 CLS
20 VL=2
30 E=VL^2
40 N=-VL
50 M=VL*10
60 D=20/VL
70 DI=VL\3
80 RE=VL MOD 3
90 A=VL+VL
100 S=10-VL
0999 ?"========================"
1000 ?"Exponenciacao    =>";E 
1010 ?"Negativo         =>";N
1020 ?"Multiplicacao    =>";M 
1030 ?"Divisao          =>";D 
1040 ?"Divisao Inteira  =>";DI
1050 ?"Resto da divisao =>";RE
1060 ?"Adicao           =>";A
1070 ?"Subtracao        =>";S
1080 ?"========================"